services:
  postgres:
    image: postgres:${POSTGRES_TAG}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kubenews"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_docker_vol:/var/lib/postgresql/data
    networks:
      - kube_news_net
  kube_news:
    image: cassiobotaro/kube-news:${KUBE_NEWS_TAG}
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - kube_news_net
    environment:
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${POSTGRES_DB}
      DB_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_docker_vol:

networks:
  kube_news_net:
    driver: bridge
